# === General Settings ===
set -g status-position top
set -g set-clipboard external
set -g detach-on-destroy off
set -g history-limit 1000000
set -g mouse on
set -g focus-events on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# === vi like copy mode in tmux ===
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# === Keybindings ===
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded tmux config"
bind-key \\ display-popup

# === TPM Plugins List ===
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# === Catppuccin Theme Settings ===
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "default"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# === Statusline Configuration ===
set -g status-left "#{prefix_highlight} #{E:@catppuccin_status_session} "
set -g status-left-length 50
set -g status-right "#[fg=#a6e3a1]🖥  #{cpu_percentage} #[fg=#89b4fa]💾 #{ram_percentage} #{E:@catppuccin_status_date_time} CS: #{continuum_status}"
set -g status-right-length 100
set -g @catppuccin_date_time_text " %a %b %d %H:%M"

# === Resurrect & Continuum Automation Settings ===
# These must be set before TPM initializes the plugins
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-save-interval '15'

# Initialize TMUX plugin manager (Keep at the absolute bottom)
run '~/.tmux/plugins/tpm/tpm'

