# === General Settings ===
set -g status-position top
set -g set-clipboard external
set -g detach-on-destroy off
set -g history-limit 1000000
set -g mouse on
set -g focus-events on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Automatically restore the last saved environment on tmux start
set -g @continuum-restore 'on'

# Automatically start tmux when the computer/server turns on
set -g @continuum-boot 'on'

# === Keybindings ===
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded tmux config"
bind-key \\ display-popup

# === Catppuccin ===
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "default"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# === Statusline ===
set -g status-left "#{prefix_highlight} #{E:@catppuccin_status_session} "
set -g status-left-length 50
set -g status-right "#[fg=#a6e3a1]🖥  #{cpu_percentage} #[fg=#89b4fa]💾 #{ram_percentage} #{E:@catppuccin_status_date_time} CS: #{continuum_status}"
set -g status-right-length 100
set -g @catppuccin_date_time_text " %a %b %d %H:%M"

# === TPM ===
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Initialize TMUX plugin manager (keep at very bottom)
run '~/.tmux/plugins/tpm/tpm'
